name: Android

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.5
      
    - name: set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: gradle

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3.3.2
      with:
        gradle-version: 8.6

    - name: Executable Permission
      run: chmod +x gradlew

    - name: Build Package
      run: ./gradlew clean build --debug --info --scan --stacktrace