name: Dart

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.3
      
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1.6.4
      
    - name: Analyze Package
      run: dart analyze lib
      
    - name: Document Package
      run: dart doc .

    - name: Environment Information
      run: dart info 
      
    - name: Fix Package Dry Run 
      run: dart fix lib --dry-run
   
    - name: Fix Package Apply
      run: dart fix lib --apply
      
    - name: Format Package 
      run: dart format lib
      
    - name: Get Packages
      run: dart pub get
      
    - name: Dependency Graph
      run: dart pub deps
      
    - name: Upgrade Packages
      run: dart pub upgrade
      
    - name: Run Package
      run: dart run lib/main.dart
      
    - name: Run Test
      run: dart test
      
    - name: Compile Package
      run: dart compile exe lib/main.dart --output /bin/linux/dart_application
