name: Flutter

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.5
      
    - name: Install Flutter
      run: sudo snap install flutter --classic

    - name: Run Doctor
      run: flutter doctor
      
    - name: Analyze Package
      run: flutter analyze lib

    - name: Environment Information
      run: dart info
   
    - name: Fix Package Dry Run 
      run: dart fix lib --dry-run
   
    - name: Fix Package Apply
      run: dart fix lib --apply
      
    - name: Get Packages
      run: flutter pub get
      
    - name: Dependency Graph
      run: flutter pub deps
      
    - name: Upgrade Packages
      run: flutter pub upgrade
      
    - name: Run Test
      run: flutter test
      
    - name: Build Package APK
      run: flutter build apk lib/main.dart /bin/apk/flutter_application
  
    - name: Build Package Linux
      run: flutter build linux lib/main.dart /bin/linux/flutter_application
  
    - name: Build Package Web
      run: flutter build web lib/main.dart /bin/web/flutter_application
