name: Go

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
    
    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: 1.21
        
    - name: Document Package
      run: go doc 
      
    - name: Environment Information
      run: go env
        
    - name: Fix Package
      run: go fix ./lib
      
    - name: Format Package
      run: go fmt ./lib
      
    - name: Get Packages
      run: go get
      
    - name: List Packages
      run: go list
      
    - name: List Modules
      run: go list -m
      
    - name: Download Packages
      run: go mod download

    - name: Dependency Graph
      run: go mod graph
      
    - name: Verify Module
      run: go mod verify
      
    - name: Run Package
      run: go run ./lib/main.go

    - name: Run Test
      run: go test -v ./test
      
    - name: Go Version
      run: go version
      
    - name: Vet Package
      run: go vet ./lib
      
    - name: Synchronize Workspace
      run: go work sync
      
    - name: Use Workspace
      run: go work use ./
      
    - name: Build Package Darwin AMD64
      run: GOOS=darwin GOARCH=amd64 go build -o ./bin/darwin/amd64/go_application ./lib/main.go
      
    - name: Build Package Darwin ARM64
      run: GOOS=darwin GOARCH=arm64 go build -o ./bin/darwin/arm64/go_application ./lib/main.go
      
    - name: Build Package Linux AMD64
      run: GOOS=linux GOARCH=amd64 go build -o ./bin/linux/amd64/go_application ./lib/main.go
    
    - name: Build Package Linux ARM64
      run: GOOS=linux GOARCH=arm64 go build -o ./bin/linux/arm64/go_application ./lib/main.go
    
    - name: Build Package Windows AMD64
      run: GOOS=windows GOARCH=amd64 go build -o ./bin/windows/amd64/go_application.exe ./lib/main.go
      
    - name: Build Package Windows ARM64
      run: GOOS=windows GOARCH=arm64 go build -o ./bin/windows/arm64/go_application.exe ./lib/main.go
