name: Gradle

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.5
      
    - name: set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: gradle
        cache-dependency-path: | # optional
          sub-project/**/*.gradle*
          sub-project/**/*.gradle.kts*
          sub-project/**/gradle-wrapper.properties
          sub-project/gradle/*.versions.toml
          sub-project/buildSrc/**/Dependencies.kt
          sub-project/buildSrc/**/Versions.kt
          sub-project/**/versions.properties

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3.3.2
      with:
        arguments: clean build --debug --info --scan --stacktrace
        gradle-version: 8.6