name: Snapcraft

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.2
     
    - name: Install Snapcraft
      run: sudo snap install snapcraft --classic
      
    - name: Build Snap
      run: snapcraft