name: Swift

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 1-5"

jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4.1.4

    - name: Resolve Packages
      run: swift package resolve

    - name: Update Packages
      run: swift package update

    - name: Run Package
      run: swift run ./lib/main.swift
    
    - name: Run Test
      run: swift test

    - name: Build Package
      run: swift build